import { EVENT_TYPES, EVENT_STATUS, REGISTRATION_STATUS, ORGANIZER_CATEGORIES, EVENT_CATEGORIES } from './constants';

// Mock Events Data
export const MOCK_EVENTS = [
  {
    id: 1,
    title: 'Tech Conference 2026',
    date: '2026-03-15',
    time: '09:00',
    location: 'Convention Center, San Francisco',
    description: 'Annual technology conference featuring the latest innovations in AI and software development. Join us for inspiring talks, hands-on workshops, and networking opportunities with industry leaders.',
    category: 'Technology',
    organizer: 'Tech Events Inc.',
    organizerId: 1,
    capacity: 500,
    registered: 234,
    type: EVENT_TYPES.NORMAL,
    status: EVENT_STATUS.PUBLISHED,
    eligibility: 'All',
    registrationDeadline: '2026-03-10',
    eventStartDate: '2026-03-15',
    eventEndDate: '2026-03-17',
    registrationFee: 500,
    tags: ['AI', 'Software', 'Innovation'],
    customForm: [
      { id: 'f1', type: 'text', label: 'T-Shirt Size', required: true, options: ['S', 'M', 'L', 'XL'] },
      { id: 'f2', type: 'textarea', label: 'Why do you want to attend?', required: true },
    ],
  },
  {
    id: 2,
    title: 'Music Festival',
    date: '2026-04-20',
    time: '18:00',
    location: 'Central Park, New York',
    description: 'Summer music festival featuring local and international artists. Experience amazing performances across multiple stages with food trucks and art installations.',
    category: 'Entertainment',
    organizer: 'Live Nation',
    organizerId: 2,
    capacity: 1000,
    registered: 678,
    type: EVENT_TYPES.NORMAL,
    status: EVENT_STATUS.PUBLISHED,
    eligibility: 'All',
    registrationDeadline: '2026-04-15',
    eventStartDate: '2026-04-20',
    eventEndDate: '2026-04-22',
    registrationFee: 1500,
    tags: ['Music', 'Festival', 'Entertainment'],
    customForm: [],
  },
  {
    id: 3,
    title: 'Felicity T-Shirt',
    date: '2026-02-20',
    time: '10:00',
    location: 'IIIT Hyderabad',
    description: 'Official Felicity 2026 T-Shirt. Premium quality cotton with vibrant festival design. Available in multiple sizes and colors.',
    category: 'Merchandise',
    organizer: 'Felicity Team',
    organizerId: 3,
    capacity: 500,
    registered: 145,
    type: EVENT_TYPES.MERCHANDISE,
    status: EVENT_STATUS.PUBLISHED,
    eligibility: 'All',
    registrationDeadline: '2026-02-18',
    eventStartDate: '2026-02-20',
    eventEndDate: '2026-02-20',
    registrationFee: 300,
    tags: ['Merchandise', 'T-Shirt'],
    merchandiseDetails: {
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      colors: ['Black', 'White', 'Navy Blue'],
      stock: 355,
      purchaseLimit: 2,
    },
  },
  {
    id: 4,
    title: 'Hackathon 2026',
    date: '2026-03-25',
    time: '08:00',
    location: 'IIIT Hyderabad',
    description: '36-hour hackathon with amazing prizes. Build innovative solutions to real-world problems. Team size: 2-4 members.',
    category: 'Competition',
    organizer: 'CodeClub IIIT',
    organizerId: 4,
    capacity: 200,
    registered: 89,
    type: EVENT_TYPES.NORMAL,
    status: EVENT_STATUS.PUBLISHED,
    eligibility: 'All',
    registrationDeadline: '2026-03-20',
    eventStartDate: '2026-03-25',
    eventEndDate: '2026-03-27',
    registrationFee: 0,
    tags: ['Hackathon', 'Coding', 'Competition'],
    customForm: [
      { id: 'f1', type: 'text', label: 'Team Name', required: true },
      { id: 'f2', type: 'number', label: 'Team Size (2-4)', required: true },
      { id: 'f3', type: 'textarea', label: 'Previous Hackathon Experience', required: false },
    ],
    teamBased: true,
    teamSize: { min: 2, max: 4 },
  },
  {
    id: 5,
    title: 'Photography Workshop',
    date: '2026-02-28',
    time: '14:00',
    location: 'Art Studio, Building 3',
    description: 'Learn professional photography techniques from award-winning photographers. Bring your camera or smartphone.',
    category: 'Workshop',
    organizer: 'PhotoClub IIIT',
    organizerId: 5,
    capacity: 50,
    registered: 43,
    type: EVENT_TYPES.NORMAL,
    status: EVENT_STATUS.PUBLISHED,
    eligibility: 'IIIT Only',
    registrationDeadline: '2026-02-25',
    eventStartDate: '2026-02-28',
    eventEndDate: '2026-02-28',
    registrationFee: 200,
    tags: ['Photography', 'Workshop', 'Art'],
    customForm: [
      { id: 'f1', type: 'select', label: 'Experience Level', required: true, options: ['Beginner', 'Intermediate', 'Advanced'] },
      { id: 'f2', type: 'checkbox', label: 'I have my own camera', required: false },
    ],
  },
];

// Mock Organizers Data
export const MOCK_ORGANIZERS = [
  {
    id: 1,
    name: 'Tech Events Inc.',
    category: ORGANIZER_CATEGORIES[0],
    description: 'Leading technology event organizer hosting conferences and workshops worldwide.',
    contactEmail: 'contact@techevents.com',
    contactNumber: '+1-555-0100',
    followers: 1234,
    totalEvents: 15,
    upcomingEvents: 3,
  },
  {
    id: 2,
    name: 'Live Nation',
    category: ORGANIZER_CATEGORIES[1],
    description: 'Global entertainment company producing live music events and festivals.',
    contactEmail: 'info@livenation.com',
    contactNumber: '+1-555-0200',
    followers: 5678,
    totalEvents: 45,
    upcomingEvents: 8,
  },
  {
    id: 3,
    name: 'Felicity Team',
    category: ORGANIZER_CATEGORIES[5],
    description: 'Official team organizing IIIT Hyderabad\'s annual technical and cultural fest.',
    contactEmail: 'felicity@iiit.ac.in',
    contactNumber: '+91-40-6653-1000',
    followers: 3456,
    totalEvents: 50,
    upcomingEvents: 12,
  },
  {
    id: 4,
    name: 'CodeClub IIIT',
    category: ORGANIZER_CATEGORIES[0],
    description: 'Student-run technical club focusing on competitive programming and hackathons.',
    contactEmail: 'codeclub@students.iiit.ac.in',
    contactNumber: '+91-98765-43210',
    followers: 890,
    totalEvents: 20,
    upcomingEvents: 4,
  },
  {
    id: 5,
    name: 'PhotoClub IIIT',
    category: ORGANIZER_CATEGORIES[1],
    description: 'Photography enthusiasts club conducting workshops and photo walks.',
    contactEmail: 'photoclub@students.iiit.ac.in',
    contactNumber: '+91-98765-43211',
    followers: 456,
    totalEvents: 12,
    upcomingEvents: 2,
  },
];

// Mock Registrations Data
export const MOCK_REGISTRATIONS = [
  {
    id: 'REG001',
    userId: 'user1',
    eventId: 1,
    registrationDate: '2026-02-01',
    status: REGISTRATION_STATUS.CONFIRMED,
    ticketId: 'TKT001',
    paymentStatus: 'Paid',
    customFormData: {
      'T-Shirt Size': 'L',
      'Why do you want to attend?': 'Interested in AI and networking',
    },
  },
  {
    id: 'REG002',
    userId: 'user1',
    eventId: 4,
    registrationDate: '2026-02-10',
    status: REGISTRATION_STATUS.CONFIRMED,
    ticketId: 'TKT002',
    paymentStatus: 'Paid',
    teamName: 'Code Warriors',
    customFormData: {
      'Team Name': 'Code Warriors',
      'Team Size (2-4)': '3',
    },
  },
];

// Mock Users Data
export const MOCK_USERS = [
  {
    id: 'user1',
    email: 'participant@iiit.ac.in',
    password: 'password123', // In real app, this would be hashed
    role: 'Participant',
    participantType: 'IIIT',
    firstName: 'John',
    lastName: 'Doe',
    college: 'IIIT Hyderabad',
    contactNumber: '+91-98765-43210',
    interests: ['Web Development', 'Machine Learning', 'Gaming'],
    followedClubs: [3, 4, 5],
  },
  {
    id: 'user2',
    email: 'organizer@iiit.ac.in',
    password: 'password123',
    role: 'Organizer',
    organizerId: 3,
    organizerName: 'Felicity Team',
    category: 'Fest Team',
    description: 'Official Felicity organizing team',
    contactEmail: 'felicity@iiit.ac.in',
    contactNumber: '+91-40-6653-1000',
  },
  {
    id: 'user3',
    email: 'admin@iiit.ac.in',
    password: 'admin123',
    role: 'Admin',
    firstName: 'Admin',
    lastName: 'User',
  },
];

// Generate more mock events for testing
export const generateMockEvents = (count = 20) => {
  const titles = [
    'AI Workshop', 'Dance Competition', 'Food Festival', 'Gaming Tournament',
    'Startup Pitch', 'Art Exhibition', 'Coding Sprint', 'Music Night',
    'Sports Day', 'Book Fair', 'Science Expo', 'Film Screening',
  ];
  
  const locations = [
    'Auditorium', 'Sports Complex', 'Main Lawn', 'Seminar Hall',
    'Lab Complex', 'Open Air Theatre', 'Conference Room', 'Campus Ground',
  ];
  
  const events = [...MOCK_EVENTS];
  
  for (let i = 0; i < count; i++) {
    const baseDate = new Date('2026-02-15');
    baseDate.setDate(baseDate.getDate() + Math.floor(Math.random() * 90));
    
    events.push({
      id: MOCK_EVENTS.length + i + 1,
      title: `${titles[i % titles.length]} ${Math.floor(Math.random() * 100)}`,
      date: baseDate.toISOString().split('T')[0],
      time: `${String(Math.floor(Math.random() * 12) + 8).padStart(2, '0')}:00`,
      location: locations[i % locations.length],
      description: `An exciting event featuring various activities and opportunities for participants to learn and engage.`,
      category: EVENT_CATEGORIES[i % EVENT_CATEGORIES.length],
      organizer: MOCK_ORGANIZERS[i % MOCK_ORGANIZERS.length].name,
      organizerId: (i % MOCK_ORGANIZERS.length) + 1,
      capacity: Math.floor(Math.random() * 400) + 100,
      registered: Math.floor(Math.random() * 200),
      type: Math.random() > 0.8 ? EVENT_TYPES.MERCHANDISE : EVENT_TYPES.NORMAL,
      status: EVENT_STATUS.PUBLISHED,
      eligibility: ['All', 'IIIT Only', 'External Only'][Math.floor(Math.random() * 3)],
      registrationDeadline: new Date(baseDate.getTime() - 86400000 * 3).toISOString().split('T')[0],
      eventStartDate: baseDate.toISOString().split('T')[0],
      eventEndDate: baseDate.toISOString().split('T')[0],
      registrationFee: Math.floor(Math.random() * 1000),
      tags: ['Event', 'Activity'],
      customForm: [],
    });
  }
  
  return events;
};
